/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.hwak.client.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RequestDto
 */
@JsonPropertyOrder({
  RequestDto.JSON_PROPERTY_ID,
  RequestDto.JSON_PROPERTY_NAME,
  RequestDto.JSON_PROPERTY_EMAIL,
  RequestDto.JSON_PROPERTY_PHONE,
  RequestDto.JSON_PROPERTY_ADDRESS,
  RequestDto.JSON_PROPERTY_CITY,
  RequestDto.JSON_PROPERTY_STATE,
  RequestDto.JSON_PROPERTY_ZIP,
  RequestDto.JSON_PROPERTY_COUNTRY,
  RequestDto.JSON_PROPERTY_PASSWORD,
  RequestDto.JSON_PROPERTY_CONFIRM_PASSWORD,
  RequestDto.JSON_PROPERTY_CREATED,
  RequestDto.JSON_PROPERTY_UPDATED,
  RequestDto.JSON_PROPERTY_DELETED,
  RequestDto.JSON_PROPERTY_MDM_ID,
  RequestDto.JSON_PROPERTY_COUNT_OF_UNSUCCESSFUL_LOGIN,
  RequestDto.JSON_PROPERTY_AMOUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-25T23:00:45.143445272+03:00[Europe/Moscow]", comments = "Generator version: 7.11.0")
public class RequestDto {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @javax.annotation.Nullable
  private String email;

  public static final String JSON_PROPERTY_PHONE = "phone";
  @javax.annotation.Nullable
  private String phone;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  @javax.annotation.Nullable
  private String address;

  public static final String JSON_PROPERTY_CITY = "city";
  @javax.annotation.Nullable
  private String city;

  public static final String JSON_PROPERTY_STATE = "state";
  @javax.annotation.Nullable
  private String state;

  public static final String JSON_PROPERTY_ZIP = "zip";
  @javax.annotation.Nullable
  private String zip;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  @javax.annotation.Nullable
  private String country;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  @javax.annotation.Nullable
  private String password;

  public static final String JSON_PROPERTY_CONFIRM_PASSWORD = "confirmPassword";
  @javax.annotation.Nullable
  private String confirmPassword;

  public static final String JSON_PROPERTY_CREATED = "created";
  @javax.annotation.Nullable
  private OffsetDateTime created;

  public static final String JSON_PROPERTY_UPDATED = "updated";
  @javax.annotation.Nullable
  private OffsetDateTime updated;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  @javax.annotation.Nullable
  private Boolean deleted;

  public static final String JSON_PROPERTY_MDM_ID = "mdmId";
  @javax.annotation.Nullable
  private UUID mdmId;

  public static final String JSON_PROPERTY_COUNT_OF_UNSUCCESSFUL_LOGIN = "countOfUnsuccessfulLogin";
  @javax.annotation.Nullable
  private Integer countOfUnsuccessfulLogin;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @javax.annotation.Nullable
  private BigDecimal amount;

  public RequestDto() {
  }

  public RequestDto id(@javax.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  public RequestDto name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public RequestDto email(@javax.annotation.Nullable String email) {
    
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }

  public RequestDto phone(@javax.annotation.Nullable String phone) {
    
    this.phone = phone;
    return this;
  }

  /**
   * Get phone
   * @return phone
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhone() {
    return phone;
  }


  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhone(@javax.annotation.Nullable String phone) {
    this.phone = phone;
  }

  public RequestDto address(@javax.annotation.Nullable String address) {
    
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(@javax.annotation.Nullable String address) {
    this.address = address;
  }

  public RequestDto city(@javax.annotation.Nullable String city) {
    
    this.city = city;
    return this;
  }

  /**
   * Get city
   * @return city
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCity() {
    return city;
  }


  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCity(@javax.annotation.Nullable String city) {
    this.city = city;
  }

  public RequestDto state(@javax.annotation.Nullable String state) {
    
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@javax.annotation.Nullable String state) {
    this.state = state;
  }

  public RequestDto zip(@javax.annotation.Nullable String zip) {
    
    this.zip = zip;
    return this;
  }

  /**
   * Get zip
   * @return zip
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ZIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getZip() {
    return zip;
  }


  @JsonProperty(JSON_PROPERTY_ZIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setZip(@javax.annotation.Nullable String zip) {
    this.zip = zip;
  }

  public RequestDto country(@javax.annotation.Nullable String country) {
    
    this.country = country;
    return this;
  }

  /**
   * Get country
   * @return country
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }

  public RequestDto password(@javax.annotation.Nullable String password) {
    
    this.password = password;
    return this;
  }

  /**
   * Get password
   * @return password
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPassword() {
    return password;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassword(@javax.annotation.Nullable String password) {
    this.password = password;
  }

  public RequestDto confirmPassword(@javax.annotation.Nullable String confirmPassword) {
    
    this.confirmPassword = confirmPassword;
    return this;
  }

  /**
   * Get confirmPassword
   * @return confirmPassword
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONFIRM_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConfirmPassword() {
    return confirmPassword;
  }


  @JsonProperty(JSON_PROPERTY_CONFIRM_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfirmPassword(@javax.annotation.Nullable String confirmPassword) {
    this.confirmPassword = confirmPassword;
  }

  public RequestDto created(@javax.annotation.Nullable OffsetDateTime created) {
    
    this.created = created;
    return this;
  }

  /**
   * Get created
   * @return created
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreated() {
    return created;
  }


  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreated(@javax.annotation.Nullable OffsetDateTime created) {
    this.created = created;
  }

  public RequestDto updated(@javax.annotation.Nullable OffsetDateTime updated) {
    
    this.updated = updated;
    return this;
  }

  /**
   * Get updated
   * @return updated
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdated() {
    return updated;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdated(@javax.annotation.Nullable OffsetDateTime updated) {
    this.updated = updated;
  }

  public RequestDto deleted(@javax.annotation.Nullable Boolean deleted) {
    
    this.deleted = deleted;
    return this;
  }

  /**
   * Get deleted
   * @return deleted
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDeleted() {
    return deleted;
  }


  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleted(@javax.annotation.Nullable Boolean deleted) {
    this.deleted = deleted;
  }

  public RequestDto mdmId(@javax.annotation.Nullable UUID mdmId) {
    
    this.mdmId = mdmId;
    return this;
  }

  /**
   * Get mdmId
   * @return mdmId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MDM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getMdmId() {
    return mdmId;
  }


  @JsonProperty(JSON_PROPERTY_MDM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMdmId(@javax.annotation.Nullable UUID mdmId) {
    this.mdmId = mdmId;
  }

  public RequestDto countOfUnsuccessfulLogin(@javax.annotation.Nullable Integer countOfUnsuccessfulLogin) {
    
    this.countOfUnsuccessfulLogin = countOfUnsuccessfulLogin;
    return this;
  }

  /**
   * Get countOfUnsuccessfulLogin
   * @return countOfUnsuccessfulLogin
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNT_OF_UNSUCCESSFUL_LOGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCountOfUnsuccessfulLogin() {
    return countOfUnsuccessfulLogin;
  }


  @JsonProperty(JSON_PROPERTY_COUNT_OF_UNSUCCESSFUL_LOGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountOfUnsuccessfulLogin(@javax.annotation.Nullable Integer countOfUnsuccessfulLogin) {
    this.countOfUnsuccessfulLogin = countOfUnsuccessfulLogin;
  }

  public RequestDto amount(@javax.annotation.Nullable BigDecimal amount) {
    
    this.amount = amount;
    return this;
  }

  /**
   * Get amount
   * @return amount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmount(@javax.annotation.Nullable BigDecimal amount) {
    this.amount = amount;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestDto requestDto = (RequestDto) o;
    return Objects.equals(this.id, requestDto.id) &&
        Objects.equals(this.name, requestDto.name) &&
        Objects.equals(this.email, requestDto.email) &&
        Objects.equals(this.phone, requestDto.phone) &&
        Objects.equals(this.address, requestDto.address) &&
        Objects.equals(this.city, requestDto.city) &&
        Objects.equals(this.state, requestDto.state) &&
        Objects.equals(this.zip, requestDto.zip) &&
        Objects.equals(this.country, requestDto.country) &&
        Objects.equals(this.password, requestDto.password) &&
        Objects.equals(this.confirmPassword, requestDto.confirmPassword) &&
        Objects.equals(this.created, requestDto.created) &&
        Objects.equals(this.updated, requestDto.updated) &&
        Objects.equals(this.deleted, requestDto.deleted) &&
        Objects.equals(this.mdmId, requestDto.mdmId) &&
        Objects.equals(this.countOfUnsuccessfulLogin, requestDto.countOfUnsuccessfulLogin) &&
        Objects.equals(this.amount, requestDto.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, email, phone, address, city, state, zip, country, password, confirmPassword, created, updated, deleted, mdmId, countOfUnsuccessfulLogin, amount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    confirmPassword: ").append(toIndentedString(confirmPassword)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    mdmId: ").append(toIndentedString(mdmId)).append("\n");
    sb.append("    countOfUnsuccessfulLogin: ").append(toIndentedString(countOfUnsuccessfulLogin)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

